const OUNCE = 'OUNCE';
const POUND = 'POUND';
const GRAMS = 'GRAMS';
const KILOGRAM = 'KILOGRAM';
const MILLIGRAM = 'MILLIGRAM';

const LITRE = 'LITRE';
const MILLILITER = 'MILLILITER';
const DECILITER = 'DECILITER';
const TEASPOON = 'TEASPOON';
const TABLESPOON = 'TABLESPOON';
const GALLON = 'GALLON';
const QUART = 'QUART';
const FLUID_ONCE = 'FLUID_ONCE';
const GILL = 'GILL';
const CUP = 'CUP';

module.exports = {
  MEASURES: [
    OUNCE,
    POUND,
    GRAMS,
    KILOGRAM,
    MILLIGRAM,

    LITRE,
    MILLILITER,
    DECILITER,
    TEASPOON,
    TABLESPOON,
    GALLON,
    QUART,
    FLUID_ONCE,
    GILL,
    CUP,
  ],

  OUNCE,
  POUND,
  GRAMS,
  KILOGRAM,
  MILLIGRAM,
  LITRE,
  MILLILITER,
  DECILITER,
  TEASPOON,
  TABLESPOON,
  GALLON,
  QUART,
  FLUID_ONCE,
  GILL,
  CUP,
};
